### ISSUE TITLE
Actualizar uso de survey parser

### ISSUE THREAD

**Issue by pcastelln** [alercebroker/prv_candidates_step#24]
```[tasklist]
### Tasks
- [ ] Actualizar dependencia de survey parser
- [ ] Actualizar subclase definida en prv del modelo de survey parser para PrvDetections y non detections
- [ ] Incluir campo `has_stamp` en detections (True para la alerta principal, False para las prv_detections)
- [ ] Modificar esquema de salida. Debería tener `aid`, `detections` y `non_detections`
```
